from enum import IntEnum


class TrafficState(IntEnum):
    NORTH_SOUTH_LEFT_GREEN = 0
    NORTH_SOUTH_LEFT_YELLOW = 1
    NORTH_SOUTH_LEFT_RED = 2
    NORTH_SOUTH_STRAIGHT_GREEN = 3
    NORTH_SOUTH_STRAIGHT_YELLOW = 4
    NORTH_SOUTH_STRAIGHT_RED = 5
    NORTH_SOUTH_RIGHT_GREEN = 6
    NORTH_SOUTH_RIGHT_YELLOW = 7
    NORTH_SOUTH_RIGHT_RED = 8
    EAST_WEST_LEFT_GREEN = 9
    EAST_WEST_LEFT_YELLOW = 10
    EAST_WEST_LEFT_RED = 11
    EAST_WEST_STRAIGHT_GREEN = 12
    EAST_WEST_STRAIGHT_YELLOW = 13
    EAST_WEST_STRAIGHT_RED = 14
    EAST_WEST_RIGHT_GREEN = 15
    EAST_WEST_RIGHT_YELLOW = 16
    EAST_WEST_RIGHT_RED = 17
